### ISSUE TITLE
Connectivity issues - mysmartblinds bridge spinning yellow / green light

### ISSUE THREAD

**Issue by gregmichael** [apexad/homebridge-mysmartblinds-bridge#33]
Having connectivity issues, thinking it was due to v2.2.0

My bridge (For blinds) was not connecting to homebridge or MSB plugin. After trying install/uninstall i figured i'd reach out to Tilt. Just spoke to technical support and was informed of server side issues that are ongoing. Will get an e-mail when things are back up to speed.

**Comment by apexad** [comment]
Thanks for adding this issue.  Indeed looks like Tilt servers are impacted by the AWS outage.
https://www.theverge.com/2020/11/25/21719396/amazon-web-services-aws-outage-down-internet

**Comment by apexad** [comment]
I'll keep this issue open until it's resolved.

**Comment by itsethamphetamine** [comment]
It looks like someone beat me to it. I am glad to hear this is "not just me" 
Did updates to the plugin to hopefully fix connectivity (have the yellow green ring as well). Home Bridge started back up and I received the longest chain of red error I have ever seen!

Will keep an eye on this as well.. If its an AWS issue.. then I guess I'm good here as well!

**Comment by apexad** [comment]
Curious though, it seems only the plugin/HomeKit is impacted.  The app seems to be working fine.  I'll keep investigating.

**Comment by apexad** [comment]
Hmmm, so the app is getting 504 errors back to but it may fall back to bluetooth control if it can reach the blind directly.

**Comment by itsethamphetamine** [comment]
When you control the blinds in the app it’s using direct Bluetooth. That is
always my backup.

**Comment by apexad** [comment]
I just pushed v2.2.2 up which will silence that big red error and just display 504 (which is timeout, which is the error we are seeing).

Also cleaned up the header a bit so it should be a little harder for the MySmartBlinds service differentiate the requests sent by the app and this plugin if for whatever reason they wanted to do that.

**Comment by apexad** [comment]
Right now if I don't hear back from the server the blind will not update the `current Position` and should display a 'No Response' in the app in that instant. This also ensure that requests via Siri say 'I did not hear back'.

Subsequent reboot of the Home app will probably show the blind as 'Opening'.  This is due to `target Position` and `current Position` not being in sync.

So, with this issue I am now definitely experiencing an issue where the  blind does actually open but the plugin never hears back from the server so it goes into this weird 'Opening' state.

**Should I update the current Position even on a timeout from the server?**

One solution here too might be for me to utilize some code from https://github.com/pedroserano/homebridge-mysmartblinds and fall back to bluetooth to check the status and update it accordingly.

**Comment by apexad** [comment]
Still want feedback on my question above, but it looks like this resolved now.
