### ISSUE TITLE
to do: Add config option that allows full blind motion

### ISSUE THREAD

**Issue by apexad** [apexad/homebridge-mysmartblinds-bridge#7]
**Is your feature request related to a problem? Please describe.**
Not a problem.  Just attempt to replicate MySmartBlinds app functionality.  
This would allow the blind to be closed down (0) to open (100) to closed up (200) via config option.

**Describe the solution you'd like**
Display as 2 separate blinds labeled as _Up_ and _Down_. 
The issue is how to display either blind when the blind is closed in the other direction.

**Describe alternatives you've considered**
Full range in 1 blind, such that `Closed` is _closed down_, `50% Open` is _open_, and `Open` is _closed up_

**Additional context**
Moved from README to-do section

If anyone want this feature, please let me know in the comments which approach you think makes the most sense.  (2 Different Blinds versus condensing 0-200 into 0-100)

**Comment by apexad** [comment]
Closing this for now in an effort to cleanup issues.  If anyone was really wanting this feature, please let me know and I will consider re-opening it and working on it when I can.

**Comment by randymassey** [comment]
Hey Mr. Alex…It’s Randy checking in…I’m curious, are you going to be releasing an update anytime soon on this plug-in? I know you had been tinkering with some of these backend updates… I also recall that you no longer have the blinds, I did briefly test the beta for the 2.0 version of HomeKit, and although there were some warning errors generated in the logging, everything worked… I’ve since gone back to release version, but I was just curious seeing the slew of emails that came through today. If you were going to roll all the changes into an update anytime soon and if it was going to be compliant with the new version of home bridge that will be released once it’s out of beta?My bestRandySent from my iPhoneOn Oct 23, 2024, at 10:15 AM, Alex Martin ***@***.***> wrote:﻿
Closed #7 as completed.

**Comment by apexad** [comment]
I have handed this plugin off to the core homebridge team, and no longer plan to work in this.

Will leave this issue open for any future developers though.

**Comment by randymassey** [comment]
Great thanks!  👍👍
